homepage/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views


app_name = 'homepage'

urlpatterns = [    
    path('', views.index, name='index'),
    path('custom_invoices', views.homepage, name='homepage'),
    path('sftp/', views.sftp_view, name='sftp'),    
    path('validation/', views.validation, name='validation'),  
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logged_out/', auth_views.LogoutView.as_view(template_name='registration/logged_out.html'), name='logged_out'),
    path('general_invoices/', views.homepage_invoices, name='homepage_invoices'),
    path('sftp_invoices/', views.sftp_invoices, name='sftp_invoices'),    
    path('validation_invoices/', views.validation_invoices, name='validation_invoices'),  
]

ocrweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage'))
]

homepage/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

homepage/views.py
# from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage
import pysftp, os
from django.shortcuts import render, redirect


from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import LoginForm

from django.contrib.auth.decorators import login_required

import time
import os
from urllib.parse import urlparse

from  .OCRMongoDB import document_info, document_info_new

from pdf2image import convert_from_bytes
from io import BytesIO

import base64

import paramiko
from PyPDF2 import PdfReader

# Create your views here.
def user_login(request):
  if request.method == 'POST':
    form = LoginForm(request.POST)
    if form.is_valid():
      cd = form.cleaned_data
      user = authenticate(request, username=cd['username'], password=cd['password'])
      if user is not None:
        if user.is_active:
            login(request, user)
            return HttpResponse('Authenticated Sucessfully')
        else:
            return HttpResponse('Disabled account')
      else:
          return HttpResponse('Invalid login')
    else:
      form = LoginForm()
    return render(request, 'registration/login.html', {'form':form})


def index(request):
  return render(request, 'homepage/index.html')



###### START - OCR INVOICES
file_list_param = []

@login_required
def homepage(request):
  global file_list_param
  file_list_param.clear()
  cnopts = pysftp.CnOpts()
  cnopts.hostkeys = None
  if request.method == 'POST':
    for upfile in request.FILES.getlist('files[]'):
      # print(request.FILES.getlist('files[]'))
      filename = upfile.name
      fss = FileSystemStorage()
      file = fss.save(upfile.name, upfile)
      file_url = fss.url(file)
      file_list_param.append(filename)
      with pysftp.Connection('gpt.helpbots.sg', username='root', password='EPIKLAH2023', cnopts=cnopts) as sftp:
          with sftp.cd('meggit_invoice/'):   
            sftp.put('/var/www/html/ocrweb/media/' + file)      
      os.remove('/var/www/html/ocrweb/media/' + file)
            
    return redirect('/sftp/')
  return render(request, 'homepage/home.html')

@login_required
def sftp_view(request):
  # SFTP server details
  host = 'gpt.helpbots.sg'
  port = 22  # Port number for SFTP (usually 22)
  username = 'root'
  password = 'EPIKLAH2023'
  remote_path = '/root/meggit_invoice/'

  # Connect to the SFTP server
  ssh_client = paramiko.SSHClient()
  ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
  ssh_client.connect(host, port=port, username=username, password=password)
  sftp_client = ssh_client.open_sftp()

  # List files and folders in the remote path
  file_list = sftp_client.listdir(remote_path)   

  # print(file_list_param)

  data_list = []
  for file_name in file_list_param: 
    data_dic = {}
    remote_file_path = remote_path + '/' + file_name
    remote_file = sftp_client.open(remote_file_path, 'rb')
    pdf_content = remote_file.read()
    pdf_base64 = base64.b64encode(pdf_content).decode('utf-8')
    # print('base64',pdf_content, pdf_base64)
    spreadsheet_id, page_id = document_info(file_name)
    # time.sleep(3)
    spreadsheet_url = f'https://docs.google.com/spreadsheets/d/{spreadsheet_id}/edit#gid={page_id}'
        
    data_dic['filename'] = file_name
    data_dic['base64'] = pdf_base64
    data_dic['spreadsheet_url'] = spreadsheet_url
    print(spreadsheet_url)
    data_list.append(data_dic)
   
  # Close the SFTP connection
  sftp_client.close()
  ssh_client.close() 
  return render(request, 'homepage/sftp.html', {'data_list': data_list})

@login_required
def validation(request):
  # SFTP server details
  host = 'gpt.helpbots.sg'
  port = 22  # Port number for SFTP (usually 22)
  username = 'root'
  password = 'EPIKLAH2023'
  remote_path = '/root/meggit_invoice/'

  # Connect to the SFTP server
  ssh_client = paramiko.SSHClient()
  ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
  ssh_client.connect(host, port=port, username=username, password=password)
  sftp_client = ssh_client.open_sftp()

  # List files and folders in the remote path
  file_list = sftp_client.listdir(remote_path)   


  data_list = []
  for file_name in file_list: 
    data_dic = {}
    remote_file_path = remote_path + '/' + file_name
    remote_file = sftp_client.open(remote_file_path, 'rb')
    pdf_content = remote_file.read()
    pdf_base64 = base64.b64encode(pdf_content).decode('utf-8')
    
    spreadsheet_id, page_id = document_info(file_name)
    # time.sleep(3)
    spreadsheet_url = f'https://docs.google.com/spreadsheets/d/{spreadsheet_id}/edit#gid={page_id}'
        
    data_dic['filename'] = file_name
    data_dic['base64'] = pdf_base64
    data_dic['spreadsheet_url'] = spreadsheet_url
    # print(spreadsheet_url)
    data_list.append(data_dic)
    # print(data_dic)
   
  # Close the SFTP connection
  sftp_client.close()
  ssh_client.close()

  return render(request, 'homepage/validation.html', {'data_list': data_list})

######### END - OCR INVOICES


###### START - 62 INVOICES
@login_required
def homepage_invoices(request):
  global file_list_param
  file_list_param.clear()

  cnopts = pysftp.CnOpts()
  cnopts.hostkeys = None
  if request.method == 'POST':
    for upfile in request.FILES.getlist('files[]'):
      filename = upfile.name
      # #file_list_param.append(filename)
      fss = FileSystemStorage()
      file = fss.save(upfile.name, upfile)
      file_url = fss.url(file)
      file_list_param.append(filename)
      with pysftp.Connection('gpt.helpbots.sg', username='root', password='EPIKLAH2023', cnopts=cnopts) as sftp:
          with sftp.cd('general_invoice/'):   
            sftp.put('/var/www/html/ocrweb/media/' + file)      
      os.remove('/var/www/html/ocrweb/media/' + file)

    time.sleep(30)
    return redirect('/sftp_invoices/')      
  return render(request, 'homepage/homepage_invoices.html')



@login_required
def sftp_invoices(request):
  # SFTP server details
  host = 'gpt.helpbots.sg'
  port = 22  # Port number for SFTP (usually 22)
  username = 'root'
  password = 'EPIKLAH2023'
  remote_path = '/root/general_invoice/'

  # Connect to the SFTP server
  ssh_client = paramiko.SSHClient()
  ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
  ssh_client.connect(host, port=port, username=username, password=password)
  sftp_client = ssh_client.open_sftp()

  # List files and folders in the remote path
  file_list = sftp_client.listdir(remote_path)   

  # print(file_list_param)

  data_list = []
  for file_name in file_list_param: 
    data_dic = {}
    remote_file_path = remote_path + '/' + file_name
    remote_file = sftp_client.open(remote_file_path, 'rb')
    pdf_content = remote_file.read()
    pdf_base64 = base64.b64encode(pdf_content).decode('utf-8')
    # print('base64',pdf_content, pdf_base64)
    spreadsheet_id, page_id = document_info_new(file_name)
    # time.sleep(3)
    spreadsheet_url = f'https://docs.google.com/spreadsheets/d/{spreadsheet_id}/edit#gid={page_id}'
        
    data_dic['filename'] = file_name
    data_dic['base64'] = pdf_base64
    data_dic['spreadsheet_url'] = spreadsheet_url
    print(spreadsheet_url)
    data_list.append(data_dic)
   
  # Close the SFTP connection
  sftp_client.close()
  ssh_client.close() 
  return render(request, 'homepage/sftp_invoices.html', {'data_list': data_list})

@login_required
def validation_invoices(request):
  # SFTP server details
  host = 'gpt.helpbots.sg'
  port = 22  # Port number for SFTP (usually 22)
  username = 'root'
  password = 'EPIKLAH2023'
  remote_path = '/root/general_invoice/'

  # Connect to the SFTP server
  ssh_client = paramiko.SSHClient()
  ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
  ssh_client.connect(host, port=port, username=username, password=password)
  sftp_client = ssh_client.open_sftp()

  # List files and folders in the remote path
  file_list = sftp_client.listdir(remote_path)   


  data_list = []
  for file_name in file_list: 
    data_dic = {}
    remote_file_path = remote_path + '/' + file_name
    remote_file = sftp_client.open(remote_file_path, 'rb')
    pdf_content = remote_file.read()
    pdf_base64 = base64.b64encode(pdf_content).decode('utf-8')
    
    spreadsheet_id, page_id = document_info_new(file_name)
    # time.sleep(3)
    spreadsheet_url = f'https://docs.google.com/spreadsheets/d/{spreadsheet_id}/edit#gid={page_id}'
        
    data_dic['filename'] = file_name
    data_dic['base64'] = pdf_base64
    data_dic['spreadsheet_url'] = spreadsheet_url
    # print(spreadsheet_url)
    data_list.append(data_dic)
    # print(data_dic)
   
  # Close the SFTP connection
  sftp_client.close()
  ssh_client.close()

  return render(request, 'homepage/validation_invoices.html', {'data_list': data_list})

###### END - 62 INVOICES

homepage/templates/homepage/home copy 2.html
{% extends "base.html" %}
{% block title %}Homepage{% endblock %}
{% block content %}

<div class="login-form content">
  <h1>Custom Invoices OCR Demo</h1>
  <p>Click on the "Choose File" button to upload a PDF file:</p>
  <div style="text-align: center;">
      <form method="post" enctype="multipart/form-data" id="upload-form">
          {% csrf_token %}
          <input type="file" name="files[]" accept=".pdf" id="file-input" autocomplete="off" multiple>
          <br>
          <br>
          <button id="submit-btn" style="position:fixed; left:49%; top:40%;" class="btn btn-dark" type="submit">Submit</button>
      </form>
  </div>
  
  <div style="position: absolute;" id="Progress_Status">
    <div id="myprogressBar" style="display:none;" ></div>
    <span id="progress-text"></span>
  </div>
  
</div>
<!-- <script>
  document.getElementById('upload-form').addEventListener('submit', function(e) {
    e.preventDefault();
    
    // Disable the submit button
    document.getElementById('submit-btn').disabled = true;
    
    // Show the progress bar
    var progressContainer = document.getElementById('Progress_Status');
    // progressContainer.style.display = 'block';
    
    var progressBar = document.getElementById('myprogressBar');
    progressBar.style.display = 'block';
    var progressText = document.getElementById('progress-text');
    progressBar.style.width = '0%';
    
    var files = document.querySelector('input[type="file"]').files;
    var numFiles = files.length;
    var totalTime = numFiles * 60000; // Number of files multiplied by 60 seconds
    
    
    var startTime = new Date().getTime();
    var endTime = startTime + totalTime;
    
    // Submit the form asynchronously using AJAX
    var formData = new FormData(this);
    var xhr = new XMLHttpRequest();
    xhr.open('POST', this.action, true);
    xhr.onreadystatechange = function() {
      if (xhr.readyState === 4 && xhr.status === 200) {
        // File upload completed successfully
        // ...
        
      } else if (xhr.readyState === 4 && xhr.status !== 200) {
        // File upload failed
        // ...
      }
    };
    xhr.send(formData);

    function updateProgress() {
      var currentTime = new Date().getTime();
      var elapsed = currentTime - startTime;
      var progress = Math.min((elapsed / totalTime) * 100, 100);
      
      progressBar.style.width = progress + '%';
      progressText.textContent = 'Progress: ' + progress.toFixed(2) + '%';
      
      if (currentTime < endTime) {
        setTimeout(updateProgress, 500); // Update progress every 500 milliseconds
      } else {
        progressText.textContent = 'Upload complete!';
        window.location.href = "/sftp/";
        // Redirect or update UI as needed
        // ...
        // Enable the submit button
        document.getElementById('submit-btn').disabled = false;
        // Hide the progress bar
        progressContainer.style.display = 'none';
      }
    }
    
    setTimeout(updateProgress, 500);
    
   
});
</script> -->

<script>
  document.getElementById('upload-form').addEventListener('submit', function(e) {
    e.preventDefault();
    
    // Disable the submit button
    document.getElementById('submit-btn').disabled = true;
    
    // Show the progress bar
    var progressBar = document.getElementById('myprogressBar');
    progressBar.style.display = 'block';
    var progressText = document.getElementById('progress-text');
    progressBar.style.width = '0%';

    var formData = new FormData(this);
    var xhr = new XMLHttpRequest();
    xhr.open('POST', this.action, true);
    xhr.onreadystatechange = function() {
      if (xhr.readyState === 4 && xhr.status === 200) {
        // File upload completed successfully
        // ...
        
      } else if (xhr.readyState === 4 && xhr.status !== 200) {
        // File upload failed
        // ...
      }
    };
    xhr.send(formData);
    
    var files = document.querySelector('input[type="file"]').files;
    var numFiles = files.length;
    
    var promises = []; // Array to store the promises
    
    // Process each PDF file and create a promise for each
    for (var i = 0; i < numFiles; i++) {
      var file = files[i];
      
      var promise = new Promise(function(resolve, reject) {
        var reader = new FileReader();
        reader.onload = function() {
          var arrayBuffer = this.result;
          
          pdfjsLib.getDocument(arrayBuffer).promise.then(function(pdf) {
            var numPages = pdf.numPages;
            resolve(numPages); // Resolve the promise with the number of pages
          });
        };
        
        reader.onerror = function(error) {
          reject(error); // Reject the promise in case of an error
        };
        
        reader.readAsArrayBuffer(file);
      });
      
      promises.push(promise); // Add the promise to the array
    }
    
    // Wait for all promises to be resolved
    Promise.all(promises).then(function(results) {
      // Calculate the maximum number of pages
      var maxPages = Math.max(...results);
      
      // Calculate the total progress bar time
      var totalTime = maxPages * 60000; // Assuming 60 seconds per page
      
      var startTime = new Date().getTime();
      var endTime = startTime + totalTime;
    
    function updateProgress() {
      var currentTime = new Date().getTime();
      var elapsed = currentTime - startTime;
      var progress = Math.min((elapsed / totalTime) * 100, 100);
      
      progressBar.style.width = progress + '%';
      progressText.textContent = 'Progress: ' + progress.toFixed(2) + '%';
      
      if (currentTime < endTime) {
        setTimeout(updateProgress, 500); // Update progress every 500 milliseconds
      } else {
        progressText.textContent = 'Upload complete!';
        window.location.href = "/sftp/";
        // Redirect or update UI as needed
        // ...
        // Enable the submit button
        document.getElementById('submit-btn').disabled = false;
        // Hide the progress bar
        progressBar.style.display = 'none';
      }
    }
    
    setTimeout(updateProgress, 500);
  });
});
</script>


{% endblock %}
  

homepage/templates/homepage/home copy.html
{% extends "base.html" %}
{% block title %}Homepage{% endblock %}
{% block content %}
<div class="login-form content">
  <h1>OCR Demo</h1>
  <p>Click on the "Choose File" button to upload a PDF file:</p>
  <div style="text-align: center;">
      <form method="post" enctype="multipart/form-data" id="upload-form">
          {% csrf_token %}
          <!-- <input type="file" name="upload" accept=".pdf" id="file-input" autocomplete="off" multiple> -->
          <input type="file" name="files[]" accept=".pdf" id="file-input" autocomplete="off" multiple>
          <br>
          <br>
          <!-- <button id="upload-button" style="text-align: center;" class="btn btn-dark" type="submit">Submit</button>  -->
          <button id="submit-btn" style="text-align: center;" class="btn btn-dark" type="submit">Submit</button>
      </form>
      <!-- <div id="progress-bar" ></div> -->
  </div>
  
  <div style="position: absolute;" id="Progress_Status">
    <div id="myprogressBar" style="display:none;" ></div>
    <span id="progress-text"></span>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/ssh2-sftp-client/dist/index.js"></script>
  <!-- <script>
    $(document).ready(function() {
    $('#upload-form').on('submit', function(e) {
        e.preventDefault();
        var progressBar = $('#myprogressBar');
        progressBar.css('width', '0%');
        progressBar.show();
        var startTime = new Date().getTime();
        var endTime = startTime + 30000; // 30 seconds

        function updateProgress() {
            var currentTime = new Date().getTime();
            var elapsed = currentTime - startTime;
            var progress = Math.min((elapsed / 30000) * 100, 100); // Calculate progress percentage

            progressBar.css('width', progress + '%');

            if (currentTime < endTime) {
                setTimeout(updateProgress, 500); // Update progress every 500 milliseconds
            } else {
                console.log('Upload complete!');
                window.location.href = "{% url 'homepage:sftp' %}"; // Redirect to another page
            }
        }
        setTimeout(updateProgress, 500);
      });
    });

  </script> -->
  <!-- <script>
    $(document).ready(function() {
      $('#upload-form').on('submit', function(e) {
        e.preventDefault();
        var progressBar = $('#myprogressBar');
        progressBar.css('width', '0%');
        progressBar.show();

        // var formData = new FormData(this); 
        // var fileInput = document.getElementById('file-input');
        // var files = fileInput.files;
        // for (var i = 0; i < files.length; i++) {
        //   formData.append(files[i]);
        // }
        var fileInput = document.getElementById('file-input');
        var files = fileInput.files;
        
        var formData = new FormData();
        for (var i = 0; i < files.length; i++) {
          formData.append('files[]', files[i]);
        }
        console.log(files);

        $.ajax({
          url: "{% url 'homepage:sftp' %}", // Replace with the appropriate URL for your Django view function
          type: 'POST',
          data: formData,
          processData: false,
          contentType: false,
          xhr: function() {
            var xhr = new window.XMLHttpRequest();
            xhr.upload.addEventListener('progress', function(event) {
              if (event.lengthComputable) {
                var percentComplete = (event.loaded / event.total) * 100;
                progressBar.css('width', percentComplete + '%');
              }
            });
            return xhr;
          },
          success: function(response) {
            console.log('Upload complete!');
            window.location.href = "{% url 'homepage:sftp' %}"; // Redirect to another page
          }
        });
      });
    });

   </script> -->
   
  <!-- <script>
    $(document).ready(function() {
  // Get the CSRF token from the cookie
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
        var cookie = cookies[i].trim();
        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }

  $('#upload-form').on('submit', function(e) {
    e.preventDefault();
    var progressBar = $('#myprogressBar');
    progressBar.css('width', '0%');
    progressBar.show();

    // var formData = new FormData(this); // Create FormData object with the form data
    var fileInput = document.getElementById('file-input');
    var files = fileInput.files;
    console.log(files);
    var formData = new FormData();
    for (var i = 0; i < files.length; i++) {
      formData.append('files[]', files[i]);
    }
    
    // Get the CSRF token
    var csrftoken = getCookie('csrftoken');

    // Set the CSRF token in the AJAX request headers
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
          xhr.setRequestHeader('X-CSRFToken', csrftoken);
        }
      }
    });

    $.ajax({
      url: "{% url 'homepage:sftp' %}", // Replace with the appropriate URL for your Django view function
      type: 'POST',
      data: formData,
      processData: false,
      contentType: false,
      xhr: function() {
        var xhr = new window.XMLHttpRequest();
        xhr.upload.addEventListener('progress', function(event) {
          if (event.lengthComputable) {
            var percentComplete = (event.loaded / event.total) * 100;
            progressBar.css('width', percentComplete + '%');
          }
        });
        return xhr;
      },
      success: function(response) {
        console.log('Upload complete!');
        // window.location.href = "{% url 'homepage:sftp' %}"; // Redirect to another page
      }
    });
  });
});

  </script> -->

</div>
{% endblock %}
  

homepage/templates/homepage/home.html
{% extends "base.html" %}
{% block title %}Homepage{% endblock %}
{% block content %}

<div class="login-form content">
  <h1>Custom Invoices OCR Demo</h1>
  <p>Click on the "Choose File" button to upload a PDF file:</p>
  <div style="text-align: center;">
      <form method="post" enctype="multipart/form-data" id="upload-form">
          {% csrf_token %}
          <input type="file" name="files[]" accept=".pdf" id="file-input" autocomplete="off" multiple>
          <br>
          <br>
          <button id="submit-btn" class="submit-button" type="submit">Submit</button>
          
      </form>
  </div>
  
  <div style="position: absolute;" id="Progress_Status">
    <div id="myprogressBar" style="display:none;" ></div>
    <span id="progress-text"></span>
  </div>
  
</div>

<script>
  document.getElementById('upload-form').addEventListener('submit', function(e) {
    e.preventDefault();
    var files = document.querySelector('input[type="file"]').files;
    var numFiles = files.length;
    if (files.length === 0) {
      // No files selected, display an alert message
      alert('Please select one or more files.');
      return;
    }
    // Disable the submit button
    document.getElementById('submit-btn').disabled = true;
    
    // Show the progress bar
    var progressBar = document.getElementById('myprogressBar');
    progressBar.style.display = 'block';
    var progressText = document.getElementById('progress-text');
    progressBar.style.width = '0%';

    var formData = new FormData(this);
    var xhr = new XMLHttpRequest();
    xhr.open('POST', this.action, true);
    xhr.onreadystatechange = function() {
      if (xhr.readyState === 4 && xhr.status === 200) {
        // File upload completed successfully
        // ...
        
      } else if (xhr.readyState === 4 && xhr.status !== 200) {
        // File upload failed
        // ...
      }
    };
    xhr.send(formData);
    
    
    
    var promises = []; // Array to store the promises
    // Process each PDF file and create a promise for each
    for (var i = 0; i < numFiles; i++) {
      var file = files[i];
      
      var promise = new Promise(function(resolve, reject) {
        var reader = new FileReader();
        reader.onload = function() {
          var arrayBuffer = this.result;
          
          pdfjsLib.getDocument(arrayBuffer).promise.then(function(pdf) {
            var numPages = pdf.numPages;
            resolve(numPages); // Resolve the promise with the number of pages
          });
        };
        
        reader.onerror = function(error) {
          reject(error); // Reject the promise in case of an error
        };
        
        reader.readAsArrayBuffer(file);
      });
      
      promises.push(promise); // Add the promise to the array
    }
    
    // Wait for all promises to be resolved
    Promise.all(promises).then(function(results) {
      // Calculate the maximum number of pages
      var maxPages = Math.max(...results);
      
      // Calculate the total progress bar time
      // var totalTime = maxPages * 60000; // Assuming 60 seconds per page
      var totalTime = 60000 + 10000 * (numFiles + maxPages - 2);

      var startTime = new Date().getTime();
      var endTime = startTime + totalTime;
    
    function updateProgress() {
      var currentTime = new Date().getTime();
      var elapsed = currentTime - startTime;
      var progress = Math.min((elapsed / totalTime) * 100, 100);
      
      progressBar.style.width = progress + '%';
      progressText.textContent = 'Progress: ' + progress.toFixed(2) + '%';
      
      if (currentTime < endTime) {
        setTimeout(updateProgress, 500); // Update progress every 500 milliseconds
      } else {
        progressText.textContent = 'Upload complete!';
        window.location.href = "/sftp/";
        // Redirect or update UI as needed
        // ...
        // Enable the submit button
        document.getElementById('submit-btn').disabled = false;
        // Hide the progress bar
        progressBar.style.display = 'none';
      }
    }
    
    setTimeout(updateProgress, 500);
  });
});

</script>


{% endblock %}
  

homepage/templates/homepage/home_1.html
{% extends "base.html" %}
{% block title %}Homepage{% endblock %}
{% block content %}
<div class="login-form content">
  <h1>OCR Demo</h1>
  <p>Click on the "Choose File" button to upload a PDF file:</p>
  <div style="text-align: center;">
      <form method="post" enctype="multipart/form-data" id="upload-form">
          {% csrf_token %}
          <input type="file" name="upload" accept=".pdf" id="file-input" autocomplete="off" multiple>
          <br>
          <br>
          <button id="upload-button" style="text-align: center;" class="btn btn-dark" type="submit">Submit</button> 
          <!-- <button onclick="update()" class="btn btn-dark" type="submit">Submit</button>           -->
      </form>
      <!-- <div id="progress-bar" ></div> -->
  </div>
  
  <div style="position: absolute;" id="Progress_Status">
    <div id="myprogressBar" style="display: none;" ></div>
  </div>
  <!-- <script>
    function update() {
      var element = document.getElementById("myprogressBar"); 
      // element.show();  
      // element.style.width = '0%';
      // element.classList.toggle('show-progress-bar');
      var width = 1;
      var identity = setInterval(scene, 10);
      function scene() {
        if (width >= 100) {
          clearInterval(identity);
        } else {
          width++; 
          element.style.width = width + '%'; 
        }
      }
    }
  </script> -->
  <script>
    $(document).ready(function() {
    $('#upload-button').on('submit', function(e) {
        e.preventDefault();
        var progressBar = $('#myprogressBar');
        progressBar.css('width', '0%');
        progressBar.show();
        var startTime = new Date().getTime();
        var endTime = startTime + 30000; // 30 seconds

        function updateProgress() {
            var currentTime = new Date().getTime();
            var elapsed = currentTime - startTime;
            var progress = Math.min((elapsed / 30000) * 100, 100); // Calculate progress percentage

            progressBar.css('width', progress + '%');

            if (currentTime < endTime) {
                setTimeout(updateProgress, 500); // Update progress every 500 milliseconds
            } else {
                console.log('Upload complete!');
                window.location.href = "{% url 'homepage:sftp' %}"; // Redirect to another page
            }
        }
        setTimeout(updateProgress, 500);
      });
    });

  </script>
  
</div>
{% endblock %}
  

homepage/templates/homepage/index.html
{% extends "base.html" %}
{% block title %}Logged out{% endblock %}
{% block content %}
<h1>WELCOME TO OCR DEMO</h1>
<div>
    <a  href="{% url 'homepage:homepage' %}" class="option-button">Custom Invoices OCR</a>
    <a  href="{% url 'homepage:homepage_invoices' %}" class="option-button">General Invoices OCR</a>
</div>
{% endblock %}

homepage/templates/homepage/sftp_invoices.html
{% extends "base.html" %}
{% block title %}Homepage{% endblock %}
{% block content %}
    <h3 style="padding: 5px 5px;">PDF Files List</h3>
    <ul style="padding: 5px 5px;" >
        {% for data in data_list %}    
            <li>            
                <a href="#" onclick="loadfile('{{ data.base64 }}', '{{ data.spreadsheet_url }}')">{{ data.filename }}</a>
            </li>
            <script>        
                function loadfile(base64, spreadsheetUrl) {
                    const iframe1 = document.getElementById('pdf-iframe');
                    iframe1.src = "data:application/pdf;base64," + base64;
                    // iframe1.src = "data:image/octet-stream;base64," + base64;
                    const iframe2 = document.getElementById('spreadsheet-iframe');
                    iframe2.src = spreadsheetUrl;
                    
                }
            </script>            
        {% empty %}
            <p>No data found</p>
        {% endfor %}

    </ul>    

    <div class="container">
        <div class="iframe-container lazyload">            
            <iframe id="pdf-iframe" src="" class="iframe">PDF Review</iframe>
        </div>
        
        <div class="iframe-container lazyload">
            <iframe id="spreadsheet-iframe" src="" class="iframe" >Spreadsheet Review</iframe> 
        </div>
    </div> 
{% endblock %}